/** GLSL generated by `bezier-gen` */

vec2 bezier(vec2 cp0, vec2 cp1, vec2 cp2, float t) {
    vec2 p0 = mix(cp0, cp1, t);
    vec2 p1 = mix(cp1, cp2, t);

    return mix(p0, p1, t);
}

vec2 bezier(vec2 cp0, vec2 cp1, vec2 cp2, vec2 cp3, float t) {
    vec2 p0 = mix(cp0, cp1, t);
    vec2 p1 = mix(cp1, cp2, t);
    vec2 p2 = mix(cp2, cp3, t);

    p0 = mix(p0, p1, t);
    p1 = mix(p1, p2, t);

    return mix(p0, p1, t);
}

vec2 bezier(vec2 cp0, vec2 cp1, vec2 cp2, vec2 cp3, vec2 cp4, float t) {
    vec2 p0 = mix(cp0, cp1, t);
    vec2 p1 = mix(cp1, cp2, t);
    vec2 p2 = mix(cp2, cp3, t);
    vec2 p3 = mix(cp3, cp4, t);

    p0 = mix(p0, p1, t);
    p1 = mix(p1, p2, t);
    p2 = mix(p2, p3, t);

    p0 = mix(p0, p1, t);
    p1 = mix(p1, p2, t);

    return mix(p0, p1, t);
}

/** End of GLSL generated by `bezier-gen` */
