const defaultSegmentsMap = module.exports.defaultSegmentsMap =
Array(3).fill(0).map((v, i) => i+3);

const defaultTypesMap = module.exports.defaultTypesMap =
['float', 'vec2', 'vec3', 'vec4'];


/**
 * Adapted from [`bezier`](https://github.com/hughsk/bezier) for use in generating
 * `glsl` functions.
 *
 * @param {number} [segments=3] The number of segments (control points) in the bézier.
 * @param {string} [type='float'] The data type of the bézier function.
 * @param {string} [name='bezier'] The name of the bézier function.
 */
function makeBezier(segments = 3, type = 'float', name = 'bezier') {
    segments = Math.abs(segments | 0);

    if(!segments) {
        throw new Error('Cannot make a interpolator with no elements');
    }
    else {
        let fn = '\n';

        if(segments < 2) {
            fn += '    return cp0;\n';
        }
        else if(segments < 3) {
            fn += '    return mix(cp0, cp1, t);\n';
        }
        else {
            for(let n = segments-1; n > 0; --n) {
                for(let i = 0; i < n; ++i) {
                    fn += '    '+
                        ((n === segments-1)?
                            `${type} p${i} = mix(cp${i}, cp${i+1}, t);`
                        : ((n > 1)?
                            `p${i} = mix(p${i}, p${i+1}, t);`
                        :   `return mix(p${i}, p${i+1}, t);`))+
                        '\n';
                }

                if(n > 1) {
                    fn += '\n';
                }
            }
        }

        const cps = Array(segments).fill(0).map((v, p) => `${type} cp${p}`);

        return `${type} ${name}(${cps.join(', ')}, float t) {${fn}}\n`;
    }
}

module.exports.makeBezier = makeBezier;


const makeBeziers = (segmentsMap = defaultSegmentsMap, typesMap = defaultTypesMap,
    name) =>
    '/** GLSL generated by `bezier-gen` */\n\n'+
    typesMap.map((type) =>
            segmentsMap.map((segment) => makeBezier(segment, type, name))
                .join('\n'))
        .join('\n\n')+
    '\n/** End of GLSL generated by `bezier-gen` */\n';

module.exports.makeBeziers = makeBeziers;
