/** GLSL generated by `bezier-gen` */

vec4 bezier(vec4 cp0, vec4 cp1, vec4 cp2, float t) {
    vec4 p0 = mix(cp0, cp1, t);
    vec4 p1 = mix(cp1, cp2, t);

    return mix(p0, p1, t);
}

vec4 bezier(vec4 cp0, vec4 cp1, vec4 cp2, vec4 cp3, float t) {
    vec4 p0 = mix(cp0, cp1, t);
    vec4 p1 = mix(cp1, cp2, t);
    vec4 p2 = mix(cp2, cp3, t);

    p0 = mix(p0, p1, t);
    p1 = mix(p1, p2, t);

    return mix(p0, p1, t);
}

/** End of GLSL generated by `bezier-gen` */
